export const offers = [
  {
    id: "offer1",
    title: "Great Service",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$15",
    type: "New",
    color: "#6e48aa",
  },
  {
    id: "offer2",
    title: "Beef Delicious",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$20",
    type: "New",
    color: "#6e48aa",
  },
  {
    id: "offer3",
    title: "Short Cut",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$25",
    type: "New",
    color: "#6e48aa",
  },
  {
    id: "offer4",
    title: "Quick Dig",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$27",
    type: "New",
    color: "#6e48aa",
  },
  {
    id: "offer5",
    title: "King Size",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$32",
    type: "Hot",
    color: "#f72585",
  },
  {
    id: "offer6",
    title: "Enormous Bite",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$10",
    type: "Hot",
    color: "#f72585",
  },
  {
    id: "offer7",
    title: "Short Stuff",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$31",
    type: "Hot",
    color: "#f72585",
  },
  {
    id: "offer8",
    title: "Premium Type",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$12",
    type: "Most sale",
    color: "#ff9800",
  },
  {
    id: "offer9",
    title: "Luxurious Offer",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$17",
    type: "Most sale",
    color: "#ff9800",
  },
  {
    id: "offer10",
    title: "Great Service",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$15",
    type: "Hot",
    color: "#f72585",
  },
  {
    id: "offer11",
    title: "Beef Delicious",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$22",
    type: "Most sale",
    color: "#ff9800",
  },
  {
    id: "offer12",
    title: "Short Cut",
    text: "Ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultricies nisi at scelerisque pellentesque. Nunc feugiat felis vitae.",
    price: "$28",
    type: "Hot",
    color: "#f72585",
  },
];
